import csv
import hashlib
import re
from collections import defaultdict, Counter
from pathlib import Path

REPORTS_DIR = Path("reports")
INPUT = REPORTS_DIR / "0695_GENERIC_METRIC_PERSISTENCE_DRY_RUN_R1.csv"
OUTPUT_CSV = REPORTS_DIR / "0695_GENERIC_METRIC_SEMANTIC_IDENTITY_RESOLUTION_R3.csv"
OUTPUT_MD = REPORTS_DIR / "0695_GENERIC_METRIC_SEMANTIC_IDENTITY_RESOLUTION_R3.md"

# Generic semantic anchors. These describe dimensions of a metric and are not
# tied to a specific ticker.
DIMENSION_PATTERNS = {
    "MARKET_VALUE": [
        r"dividend\s+yield\s+anualizado\s+pelo\s+valor\s+do\s+mercado",
        r"dividend\s+yield\s+anualizado.*?valor\s+de\s+mercado",
        r"\bpelo\s+valor\s+do\s+mercado\b",
        r"\bvalor\s+de\s+mercado\b",
        r"\bcota\s+mercado\b",
        r"\bmarket\s+value\b",
        r"\bmarket\s+price\b",
    ],
    "NAV": [
        r"dividend\s+yield\s+anualizado\s+pelo\s+valor\s+patrimonial",
        r"dividend\s+yield\s+anualizado.*?valor\s+patrimonial",
        r"\bpelo\s+valor\s+patrimonial\b",
        r"\bvalor\s+patrimonial\b",
        r"\bcota\s+patrimonial\b",
        r"\bnav\b",
        r"\bnet\s+asset\s+value\b",
    ],
    "LTM": [
        r"\bdividend\s+yield\s+ltm\b",
        r"\byield\s+ltm\b",
        r"\bltm\b",
    ],
}

# Explicit semantic locator markers generated by the legacy evidence pipeline.
# These are generic labels, not ticker-specific.
LOCATOR_MAP = {
    "[valor de mercado]": "MARKET_VALUE",
    "[valor patrimonial]": "NAV",
    "[market value]": "MARKET_VALUE",
    "[nav]": "NAV",
    "[ltm]": "LTM",
    "[yield ltm]": "LTM",
}

def clean(v):
    return (v or "").strip()

def stable_hash(value):
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:24]

def normalize_for_match(text):
    text = clean(text).lower()

    # Keep accented Portuguese characters intact, but normalize a few common
    # mojibake variants found in extracted legacy evidence.
    replacements = {
        "ÿ": "i",
        "ý": "i",
        "í": "i",
        "ù": "u",
        "ú": "u",
        "ã": "a",
        "õ": "o",
        "ç": "c",
        "ô": "o",
        "ó": "o",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)

    # Remove repeated whitespace only; retain textual order and punctuation.
    text = re.sub(r"\s+", " ", text)
    return text

def source_identity(row):
    return (
        clean(row.get("SHA256")),
        clean(row.get("Canonical_Ticker")) or clean(row.get("Original_Ticker")),
        clean(row.get("Metric")),
        clean(row.get("Resolved_Period")),
    )

def load_csv(path):
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as f:
            return list(csv.DictReader(f))
    except Exception:
        return []

def text_fields(row):
    chunks = []
    preferred = [
        "Relevant_Facts",
        "Evidence_Text",
        "Evidence",
        "Relevant_Fact",
        "Source_Context",
        "Source_Text",
        "Context",
    ]
    for field in preferred:
        value = clean(row.get(field))
        if value:
            chunks.append((field, value))
    return chunks

def extract_semantic_dimension(text):
    normalized = normalize_for_match(text)
    found = []

    for locator, dimension in LOCATOR_MAP.items():
        if locator in normalized:
            found.append((dimension, "EXPLICIT_LOCATOR"))

    for dimension, patterns in DIMENSION_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, normalized, flags=re.IGNORECASE):
                found.append((dimension, "EXPLICIT_TEXT_ANCHOR"))

    # Preserve first-seen ordering while de-duplicating.
    result = []
    seen = set()
    for dimension, reason in found:
        if dimension not in seen:
            result.append((dimension, reason))
            seen.add(dimension)
    return result

def extract_value_context(text, raw_value, parsed_value):
    normalized = normalize_for_match(text)
    candidates = []

    values = []
    if clean(raw_value):
        values.append(clean(raw_value).lower())
    if clean(parsed_value):
        values.append(clean(parsed_value).lower())
        if "." in clean(parsed_value):
            values.append(clean(parsed_value).replace(".", ",").lower())

    for value in values:
        pos = normalized.find(value)
        if pos >= 0:
            start = max(0, pos - 180)
            end = min(len(normalized), pos + len(value) + 220)
            candidates.append(normalized[start:end])

    return candidates

def choose_dimension_for_value(texts, raw_value, parsed_value):
    """
    Determine the semantic dimension associated with THIS value, rather than
    assigning a dimension merely because the document contains that dimension
    somewhere else.
    """
    per_dimension_hits = defaultdict(list)

    for field, text in texts:
        for context in extract_value_context(text, raw_value, parsed_value):
            dims = extract_semantic_dimension(context)
            for dimension, reason in dims:
                per_dimension_hits[dimension].append(
                    (field, context, reason)
                )

    # Prefer a uniquely supported dimension around the specific numeric value.
    ranked = sorted(
        per_dimension_hits.items(),
        key=lambda item: len(item[1]),
        reverse=True,
    )

    if not ranked:
        return "", "NOT_FOUND", "", []

    if len(ranked) == 1:
        dimension = ranked[0][0]
        strongest = ranked[0][1][0]
        return dimension, "RESOLVED", strongest[2], ranked[0][1]

    # Multiple dimensions are acceptable only when one has strictly more local
    # value-level hits than all the others.
    top_dimension, top_hits = ranked[0]
    second_hits = len(ranked[1][1])

    if len(top_hits) > second_hits:
        strongest = top_hits[0]
        return top_dimension, "RESOLVED", "VALUE_LOCAL_CONTEXT", top_hits

    return "", "REVIEW_REQUIRED", "multiple_equal_semantic_dimensions", [
        hit
        for _, hits in ranked
        for hit in hits
    ]

def build_observation_key(row, semantic_dimension):
    parts = [
        clean(row.get("Canonical_Ticker")),
        clean(row.get("Resolved_Period")),
        clean(row.get("Metric")),
        semantic_dimension or "NO_DIMENSION",
        clean(row.get("Value_Parsed")),
        clean(row.get("Resolved_Unit")),
        clean(row.get("Scale")),
        clean(row.get("SHA256")),
    ]
    return (
        f"obs:{clean(row.get('Canonical_Ticker'))}:"
        f"{clean(row.get('Resolved_Period'))}:"
        f"{clean(row.get('Metric'))}:"
        f"{stable_hash('|'.join(parts))}"
    )

def main():
    print("0695 SEMANTIC IDENTITY RESOLUTION R3")
    print("=" * 115)

    if not INPUT.exists():
        print(f"ERRO: arquivo não encontrado: {INPUT.resolve()}")
        return

    rows = load_csv(INPUT)
    print(f"Input rows: {len(rows)}")

    # Existing reports provide additional source text, but we never modify them.
    context_by_identity = defaultdict(list)

    for report_path in sorted(REPORTS_DIR.glob("*.csv")):
        if report_path.name in {
            OUTPUT_CSV.name,
            "0695_GENERIC_METRIC_SEMANTIC_IDENTITY_RESOLUTION_R3.csv",
        }:
            continue

        report_rows = load_csv(report_path)
        for row in report_rows:
            identity = source_identity(row)
            if identity not in {source_identity(r) for r in rows}:
                continue
            for field, text in text_fields(row):
                context_by_identity[identity].append({
                    "report": str(report_path),
                    "field": field,
                    "text": text,
                })

    # Also include the current candidate's own Relevant_Facts.
    for row in rows:
        identity = source_identity(row)
        for field, text in text_fields(row):
            context_by_identity[identity].append({
                "report": str(INPUT),
                "field": field,
                "text": text,
            })

    groups = defaultdict(list)
    for row in rows:
        groups[source_identity(row)].append(row)

    results = []

    for row in rows:
        identity = source_identity(row)
        siblings = groups[identity]
        texts = [
            (item["field"], item["text"])
            for item in context_by_identity.get(identity, [])
        ]

        dimension, dim_status, dim_reason, local_hits = choose_dimension_for_value(
            texts,
            row.get("Value_Raw"),
            row.get("Value_Parsed"),
        )

        values = {clean(x.get("Value_Parsed")) for x in siblings}

        if len(siblings) == 1:
            classification = "UNIQUE"
            if dim_status == "REVIEW_REQUIRED":
                identity_status = "REVIEW_REQUIRED"
            elif clean(row.get("Metric")) == "dividend_yield_annualized" and dim_status == "NOT_FOUND":
                identity_status = "REVIEW_REQUIRED"
            else:
                identity_status = "IDENTITY_READY"

        elif len(values) == 1:
            classification = "EXACT_DUPLICATE"
            identity_status = "DEDUPLICABLE"
            if not dimension:
                dimension = "NO_DIMENSION"

        else:
            classification = "SEMANTICALLY_DISTINCT_CANDIDATES"
            if dim_status == "RESOLVED":
                identity_status = "IDENTITY_READY_WITH_DIMENSION"
            else:
                identity_status = "BLOCKED_SEMANTIC_IDENTITY"

        observation_key = build_observation_key(row, dimension)

        out = dict(row)
        out["Semantic_Dimension_R3"] = dimension
        out["Semantic_Dimension_Status_R3"] = dim_status
        out["Semantic_Dimension_Reason_R3"] = dim_reason
        out["Semantic_Local_Context_Hits_R3"] = str(len(local_hits))
        out["Identity_Classification_R3"] = classification
        out["Observation_Key_R3"] = observation_key
        out["Identity_Status_R3"] = identity_status
        results.append(out)

    counts = Counter(clean(r.get("Identity_Classification_R3")) for r in results)
    statuses = Counter(clean(r.get("Identity_Status_R3")) for r in results)
    dimensions = Counter(clean(r.get("Semantic_Dimension_R3")) or "(blank)" for r in results)

    collisions = defaultdict(list)
    for row in results:
        collisions[clean(row.get("Observation_Key_R3"))].append(row)
    collisions = {
        key: items for key, items in collisions.items()
        if key and len(items) > 1
    }

    print("\nIDENTITY CLASSIFICATION")
    print("-" * 115)
    for key in ("UNIQUE", "EXACT_DUPLICATE", "SEMANTICALLY_DISTINCT_CANDIDATES"):
        print(f"{key:40}: {counts[key]}")

    print("\nIDENTITY STATUS")
    print("-" * 115)
    for key, count in statuses.most_common():
        print(f"{key:40}: {count}")

    print("\nSEMANTIC DIMENSIONS")
    print("-" * 115)
    for key, count in dimensions.most_common():
        print(f"{key:40}: {count}")

    print("\nFOCUSED REVIEW — DUPLICATE / AMBIGUOUS GROUPS")
    print("-" * 115)
    for identity, siblings in groups.items():
        if len(siblings) <= 1:
            continue

        print(f"\nSHA256={identity[0]}")
        print(f"Ticker={identity[1]}")
        print(f"Metric={identity[2]}")
        print(f"Period={identity[3]}")

        for row in results:
            if source_identity(row) != identity:
                continue
            print(
                f"  Row={clean(row.get('Row'))} | "
                f"value={clean(row.get('Value_Parsed'))} | "
                f"dimension={clean(row.get('Semantic_Dimension_R3')) or '(blank)'} | "
                f"dim_status={clean(row.get('Semantic_Dimension_Status_R3'))} | "
                f"identity={clean(row.get('Identity_Status_R3'))} | "
                f"reason={clean(row.get('Semantic_Dimension_Reason_R3'))}"
            )

    print("\nOBSERVATION KEY COLLISIONS")
    print("-" * 115)
    print(f"Colliding keys: {len(collisions)}")
    for key, items in collisions.items():
        print(f"\nKEY: {key}")
        for row in items:
            print(
                f"  Row={clean(row.get('Row'))} | "
                f"value={clean(row.get('Value_Parsed'))} | "
                f"dimension={clean(row.get('Semantic_Dimension_R3')) or '(blank)'} | "
                f"identity={clean(row.get('Identity_Status_R3'))}"
            )

    OUTPUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys()) + [
        "Semantic_Dimension_R3",
        "Semantic_Dimension_Status_R3",
        "Semantic_Dimension_Reason_R3",
        "Semantic_Local_Context_Hits_R3",
        "Identity_Classification_R3",
        "Observation_Key_R3",
        "Identity_Status_R3",
    ]

    with OUTPUT_CSV.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)

    md = [
        "# 0695 Semantic Identity Resolution R3",
        "",
        f"- Input rows: **{len(rows)}**",
        f"- Repeated source groups: **{sum(1 for x in groups.values() if len(x) > 1)}**",
        "",
        "## Classification",
    ]

    for key in ("UNIQUE", "EXACT_DUPLICATE", "SEMANTICALLY_DISTINCT_CANDIDATES"):
        md.append(f"- `{key}`: **{counts[key]}**")

    md.extend(["", "## Identity status"])
    for key, count in statuses.most_common():
        md.append(f"- `{key}`: **{count}**")

    md.extend(["", "## Semantic dimensions"])
    for key, count in dimensions.most_common():
        md.append(f"- `{key}`: **{count}**")

    md.extend(["", "## Focused repeated groups"])
    for identity, siblings in groups.items():
        if len(siblings) <= 1:
            continue

        md.append(f"### {identity[2]} / {identity[3]} / {identity[0]}")
        for row in results:
            if source_identity(row) != identity:
                continue
            md.append(
                f"- Row `{clean(row.get('Row'))}` | "
                f"value `{clean(row.get('Value_Parsed'))}` | "
                f"dimension `{clean(row.get('Semantic_Dimension_R3'))}` | "
                f"dimension_status `{clean(row.get('Semantic_Dimension_Status_R3'))}` | "
                f"identity `{clean(row.get('Identity_Status_R3'))}` | "
                f"reason `{clean(row.get('Semantic_Dimension_Reason_R3'))}`"
            )

    md.extend([
        "",
        "## Safety",
        "",
        "- No prior report was modified.",
        "- No values were selected or discarded automatically.",
        "- No metric persistence executed.",
        "- No KnowledgeBridge executed.",
        "- Vault unchanged.",
    ])

    OUTPUT_MD.write_text("\n".join(md), encoding="utf-8")

    print(f"\nCSV: {OUTPUT_CSV.resolve()}")
    print(f"MD : {OUTPUT_MD.resolve()}")
    print("Metric persistence      : NO")
    print("KnowledgeBridge         : NO")
    print("Vault changed           : NO")

if __name__ == "__main__":
    main()
