from __future__ import annotations

import csv
import hashlib
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
REPORTS = ROOT / "reports"

INPUT_CSV = REPORTS / "IIP_HISTORICAL_IDENTITY_RECONSTRUCTION_R3.csv"

OUTPUT_CSV = REPORTS / "IIP_HISTORICAL_IDENTITY_RECONSTRUCTION_R4.csv"
OUTPUT_MD = REPORTS / "IIP_HISTORICAL_IDENTITY_RECONSTRUCTION_R4.md"


# ---------------------------------------------------------------------------
# Identity model
#
# IMPORTANT:
# Ticker is a trading identifier, NOT the legal identity of the asset.
#
# The same economic/legal asset may have:
#   - historical ticker
#   - current ticker
#   - temporary ticker
#   - ticker generated by corporate event
#
# CNPJ is treated as strong evidence when available, but absence of CNPJ
# does NOT invalidate historical identity reconstruction.
# ---------------------------------------------------------------------------

TICKER_FIELDS = (
    "Ticker",
    "Original_Ticker",
    "OriginalTicker",
    "Derived_Canonical_Ticker",
    "Canonical_Ticker",
    "ticker",
)

CNPJ_FIELDS = (
    "CNPJ",
    "Cnpj",
    "cnpj",
    "CNPJ_CVM",
    "CNPJ_Fundo",
    "CNPJ_Emitente",
)

NAME_FIELDS = (
    "Name",
    "Asset_Name",
    "Fund_Name",
    "Original_Name",
    "Canonical_Name",
    "Denomination",
    "Fund_Denomination",
)

EVENT_FIELDS = (
    "Corporate_Event",
    "CorporateEvent",
    "Event",
    "Event_Type",
    "EventType",
)

PERIOD_FIELDS = (
    "Period",
    "Content_Periods",
    "Document_Period_Manifest",
    "Resolved_Period",
)


def clean(value: object) -> str:
    if value is None:
        return ""
    return str(value).strip()


def normalize(value: object) -> str:
    return " ".join(clean(value).upper().split())


def normalize_cnpj(value: object) -> str:
    value = clean(value)
    digits = "".join(ch for ch in value if ch.isdigit())
    return digits if len(digits) == 14 else normalize(value)


def get_first(row: dict, fields: tuple[str, ...]) -> str:
    for field in fields:
        value = clean(row.get(field, ""))
        if value:
            return value
    return ""


def get_all(row: dict, fields: tuple[str, ...]) -> list[str]:
    values = []

    for field in fields:
        value = clean(row.get(field, ""))
        if value:
            values.append(value)

    return values


def split_multi(value: str) -> list[str]:
    if not value:
        return []

    separators = ("|", ";", ",")

    values = [value]

    for separator in separators:
        expanded = []

        for item in values:
            expanded.extend(item.split(separator))

        values = expanded

    result = []

    for item in values:
        item = clean(item)

        if item and item not in result:
            result.append(item)

    return result


def extract_tickers(row: dict) -> list[str]:
    values = []

    for field in TICKER_FIELDS:
        values.extend(split_multi(clean(row.get(field, ""))))

    result = []

    for ticker in values:
        ticker = normalize(ticker)

        if ticker and ticker not in result:
            result.append(ticker)

    return result


def extract_cnpjs(row: dict) -> list[str]:
    result = []

    for field in CNPJ_FIELDS:
        value = normalize_cnpj(row.get(field, ""))

        if value and value not in result:
            result.append(value)

    return result


def extract_names(row: dict) -> list[str]:
    result = []

    for field in NAME_FIELDS:
        value = normalize(row.get(field, ""))

        if value and value not in result:
            result.append(value)

    return result


def extract_events(row: dict) -> list[str]:
    result = []

    for field in EVENT_FIELDS:
        value = normalize(row.get(field, ""))

        if value and value not in result:
            result.append(value)

    return result


def extract_periods(row: dict) -> list[str]:
    result = []

    for field in PERIOD_FIELDS:
        value = clean(row.get(field, ""))

        if not value:
            continue

        for period in split_multi(value):
            period = normalize(period)

            if period and period not in result:
                result.append(period)

    return result


def stable_identity_key(
    cnpjs: list[str],
    tickers: list[str],
    names: list[str],
) -> tuple[str, str]:
    """
    Identity hierarchy.

    1. Single CNPJ = strongest key.
    2. Multiple CNPJs = explicit composite key, never silently merged.
    3. No CNPJ + ticker = trading identity candidate.
    4. No CNPJ/ticker + name = weak identity candidate.
    """

    if len(cnpjs) == 1:
        return (
            "CNPJ",
            "CNPJ:" + cnpjs[0],
        )

    if len(cnpjs) > 1:
        return (
            "MULTIPLE_CNPJ",
            "MULTI_CNPJ:" + "|".join(sorted(cnpjs)),
        )

    if tickers:
        return (
            "TICKER_CLUSTER",
            "TICKER:" + "|".join(sorted(tickers)),
        )

    if names:
        digest = hashlib.sha1("|".join(sorted(names)).encode("utf-8")).hexdigest()[:16]

        return (
            "NAME_CLUSTER",
            "NAME:" + digest,
        )

    return (
        "NONE",
        "",
    )


def classify_identity(
    cnpjs: list[str],
    tickers: list[str],
    names: list[str],
    events: list[str],
) -> tuple[str, str, str]:
    """
    Returns:

        decision
        confidence
        identity_type
    """

    # Strong legal identity.
    if len(cnpjs) == 1:
        if len(tickers) > 1:
            return (
                "IDENTITY_RESOLVED",
                "HIGH",
                "LEGAL_IDENTITY_MULTI_TICKER",
            )

        return (
            "IDENTITY_RESOLVED",
            "HIGH",
            "LEGAL_IDENTITY",
        )

    # Multiple CNPJs must never be automatically merged.
    if len(cnpjs) > 1:
        return (
            "REVIEW_REQUIRED",
            "MEDIUM",
            "MULTIPLE_CNPJ",
        )

    # No CNPJ but multiple tickers can represent ticker transitions,
    # provisional tickers, emissions, bonuses or other corporate events.
    if len(tickers) > 1:
        if events:
            return (
                "REVIEW_REQUIRED",
                "MEDIUM",
                "MULTI_TICKER_EVENT_CANDIDATE",
            )

        return (
            "REVIEW_REQUIRED",
            "MEDIUM",
            "MULTI_TICKER_IDENTITY_CANDIDATE",
        )

    # One ticker without CNPJ.
    if len(tickers) == 1:
        return (
            "REVIEW_REQUIRED",
            "LOW",
            "TRADING_IDENTITY_ONLY",
        )

    # Name only.
    if names:
        return (
            "REVIEW_REQUIRED",
            "LOW",
            "NAME_ONLY",
        )

    return (
        "REVIEW_REQUIRED",
        "LOW",
        "INSUFFICIENT_IDENTITY",
    )


def main() -> int:
    print("=" * 90)
    print("IIP HISTORICAL IDENTITY RECONSTRUCTION R4")
    print("=" * 90)

    if not REPORTS.exists():
        print(f"ERROR: reports directory not found: {REPORTS}")
        return 1

    if not INPUT_CSV.exists():
        print(f"ERROR: R3 input not found: {INPUT_CSV}")
        return 1

    with INPUT_CSV.open(
        "r",
        encoding="utf-8-sig",
        newline="",
    ) as handle:
        reader = csv.DictReader(handle)
        input_rows = list(reader)

    records = []

    identity_groups = defaultdict(list)

    for index, row in enumerate(input_rows, start=1):
        tickers = extract_tickers(row)
        cnpjs = extract_cnpjs(row)
        names = extract_names(row)
        events = extract_events(row)
        periods = extract_periods(row)

        identity_type, identity_key = stable_identity_key(
            cnpjs,
            tickers,
            names,
        )

        decision, confidence, classification = classify_identity(
            cnpjs,
            tickers,
            names,
            events,
        )

        record = {
            "input_row": index,
            "identity_key_type": identity_type,
            "identity_key": identity_key,
            "decision": decision,
            "confidence": confidence,
            "identity_classification": classification,
            "cnpj_count": len(cnpjs),
            "cnpj_values": "|".join(cnpjs),
            "ticker_count": len(tickers),
            "ticker_values": "|".join(tickers),
            "historical_tickers": "|".join(tickers),
            "current_ticker_candidate": tickers[-1] if tickers else "",
            "name_values": "|".join(names),
            "corporate_events": "|".join(events),
            "period_values": "|".join(periods),
            "source_file": clean(
                row.get("source_file") or row.get("file") or row.get("File") or ""
            ),
            "source_path": clean(
                row.get("source_path") or row.get("path") or row.get("Path") or ""
            ),
        }

        records.append(record)
        identity_groups[identity_key].append(record)

    # -----------------------------------------------------------------------
    # Detect multi-ticker identity clusters.
    # -----------------------------------------------------------------------

    multi_ticker_identity_keys = set()

    for key, group in identity_groups.items():
        ticker_set = set()

        for record in group:
            for ticker in split_multi(record["historical_tickers"]):
                if ticker:
                    ticker_set.add(ticker)

        if len(ticker_set) > 1:
            multi_ticker_identity_keys.add(key)

    # -----------------------------------------------------------------------
    # Add cluster metadata.
    # -----------------------------------------------------------------------

    for record in records:
        key = record["identity_key"]

        group = identity_groups[key]

        ticker_set = set()
        cnpj_set = set()

        for item in group:
            ticker_set.update(split_multi(item["historical_tickers"]))

            cnpj_set.update(split_multi(item["cnpj_values"]))

        record["cluster_record_count"] = len(group)
        record["cluster_ticker_count"] = len(ticker_set)
        record["cluster_tickers"] = "|".join(sorted(ticker_set))
        record["cluster_cnpj_count"] = len(cnpj_set)
        record["cluster_cnpjs"] = "|".join(sorted(cnpj_set))

        if key in multi_ticker_identity_keys:
            record["multi_ticker_identity"] = "YES"
        else:
            record["multi_ticker_identity"] = "NO"

        # Important semantic distinction:
        #
        # A multi-ticker cluster is NOT automatically interpreted as a
        # corporate event. It is an identity relationship requiring evidence.
        #
        # Possible causes include:
        #   ticker change
        #   temporary ticker
        #   emission
        #   bonus
        #   subscription rights
        #   corporate restructuring
        #   other B3 event
        #
        if (
            record["multi_ticker_identity"] == "YES"
            and record["decision"] == "REVIEW_REQUIRED"
        ):
            record["identity_classification"] = "MULTI_TICKER_REVIEW"

    # -----------------------------------------------------------------------
    # Output.
    # -----------------------------------------------------------------------

    fieldnames = [
        "input_row",
        "identity_key_type",
        "identity_key",
        "decision",
        "confidence",
        "identity_classification",
        "cnpj_count",
        "cnpj_values",
        "ticker_count",
        "ticker_values",
        "historical_tickers",
        "current_ticker_candidate",
        "name_values",
        "corporate_events",
        "period_values",
        "cluster_record_count",
        "cluster_ticker_count",
        "cluster_tickers",
        "cluster_cnpj_count",
        "cluster_cnpjs",
        "multi_ticker_identity",
        "source_file",
        "source_path",
    ]

    with OUTPUT_CSV.open(
        "w",
        encoding="utf-8-sig",
        newline="",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
        )

        writer.writeheader()
        writer.writerows(records)

    decision_counts = Counter(record["decision"] for record in records)

    confidence_counts = Counter(record["confidence"] for record in records)

    classification_counts = Counter(
        record["identity_classification"] for record in records
    )

    single_cnpj = sum(1 for record in records if record["cnpj_count"] == 1)

    multiple_cnpj = sum(1 for record in records if record["cnpj_count"] > 1)

    no_cnpj = sum(1 for record in records if record["cnpj_count"] == 0)

    multi_ticker_records = sum(
        1 for record in records if record["multi_ticker_identity"] == "YES"
    )

    identity_keys = len(
        {record["identity_key"] for record in records if record["identity_key"]}
    )

    # -----------------------------------------------------------------------
    # Markdown audit report.
    # -----------------------------------------------------------------------

    md = f"""# IIP Historical Identity Reconstruction R4

## Execution safety

- Mode: READ-ONLY
- Vault modified: NO
- Persistence executed: NO
- KnowledgeBridge executed: NO
- Repository writes: NO

## Input

- Source: `{INPUT_CSV}`
- Input records: {len(records)}
- Unique identity keys: {identity_keys}

## Identity results

- IDENTITY_RESOLVED: {decision_counts.get("IDENTITY_RESOLVED", 0)}
- REVIEW_REQUIRED: {decision_counts.get("REVIEW_REQUIRED", 0)}
- BLOCKED: {decision_counts.get("BLOCKED", 0)}

## Confidence

- HIGH: {confidence_counts.get("HIGH", 0)}
- MEDIUM: {confidence_counts.get("MEDIUM", 0)}
- LOW: {confidence_counts.get("LOW", 0)}
- NONE: {confidence_counts.get("NONE", 0)}

## Identity evidence

- SINGLE_CNPJ records: {single_cnpj}
- MULTIPLE_CNPJ records: {multiple_cnpj}
- NO_CNPJ records: {no_cnpj}

## Ticker continuity

- Multi-ticker identity records: {multi_ticker_records}
- Multi-ticker identity keys: {len(multi_ticker_identity_keys)}

## Classification

"""

    for classification, count in sorted(
        classification_counts.items(),
        key=lambda item: (-item[1], item[0]),
    ):
        md += f"- `{classification}`: {count}\\n"

    md += """
## Identity model

The R4 reconstruction intentionally separates legal identity from trading
identity.

Ticker is NOT treated as the primary identity key.

The same asset may have multiple historical tickers because of:

- ticker changes;
- temporary/provisional tickers;
- emissions;
- bonus issues;
- subscription rights;
- corporate restructuring;
- denomination changes;
- other B3 corporate events.

A ticker transition therefore does not automatically create a new asset.

CNPJ is treated as strong identity evidence when available.

Multiple CNPJs are never silently merged.

Absence of CNPJ does not mean that historical continuity is impossible;
records without CNPJ remain candidates for evidence-based reconstruction.

## Persistence gate

Only `IDENTITY_RESOLVED` records with sufficiently strong identity evidence
may eventually become automatic persistence candidates.

`REVIEW_REQUIRED` records remain outside automatic persistence.

No record is persisted by this R4 stage.

## Important case

The model is designed to support relationships such as:

`CVBI11 -> PCIP11`

without assuming that the ticker change itself represents a new asset.

The same principle applies generically to other B3 assets and asset classes.

## Output

- CSV: `{OUTPUT_CSV}`
- MD: `{OUTPUT_MD}`
"""

    OUTPUT_MD.write_text(
        md,
        encoding="utf-8",
    )

    print(f"Input records              : {len(records)}")

    print(f"IDENTITY_RESOLVED          : {decision_counts.get('IDENTITY_RESOLVED', 0)}")

    print(f"REVIEW_REQUIRED            : {decision_counts.get('REVIEW_REQUIRED', 0)}")

    print(f"BLOCKED                    : {decision_counts.get('BLOCKED', 0)}")

    print(f"HIGH confidence            : {confidence_counts.get('HIGH', 0)}")

    print(f"MEDIUM confidence          : {confidence_counts.get('MEDIUM', 0)}")

    print(f"LOW confidence             : {confidence_counts.get('LOW', 0)}")

    print(f"SINGLE_CNPJ                : {single_cnpj}")

    print(f"MULTIPLE_CNPJ              : {multiple_cnpj}")

    print(f"NO_CNPJ                    : {no_cnpj}")

    print(f"Unique identity keys       : {identity_keys}")

    print(f"Multi-ticker identities    : {len(multi_ticker_identity_keys)}")

    print(f"Multi-ticker records       : {multi_ticker_records}")

    print(f"CSV                        : {OUTPUT_CSV}")
    print(f"MD                         : {OUTPUT_MD}")
    print()

    print("Vault modified             : NO")
    print("Persistence executed       : NO")
    print("KnowledgeBridge executed   : NO")
    print("Repository writes          : NO")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
