"""Canonical IIP asset/source catalog."""

from __future__ import annotations

from .registry import AssetRef, SourceRef


def default_assets() -> tuple[AssetRef, ...]:
    return (
        AssetRef(
            ticker="HGRU11",
            asset_class="FII",
            asset_subtype="Tijolo",
            segment="Híbrido",
            manager="Pátria",
            sources=(
                SourceRef(
                    provider="patria",
                    role="institutional_primary",
                    priority=3,
                    url="https://realestate.patria.com/tijolo/hgru",
                ),
                SourceRef(
                    provider="fnet_cvm",
                    role="regulatory",
                    priority=1,
                    url="https://fnet.bmfbovespa.com.br/",
                ),
                SourceRef(
                    provider="b3",
                    role="market_validation",
                    priority=4,
                    url="https://www.b3.com.br/",
                ),
            ),
        ),
        AssetRef(
            ticker="XPML11",
            asset_class="FII",
            asset_subtype="Tijolo",
            segment="Shopping",
            manager="XP Asset",
            sources=(
                SourceRef(
                    provider="xp_asset",
                    role="institutional_primary",
                    priority=3,
                    url="https://www.xpasset.com.br/fundos/xp-malls/",
                ),
                SourceRef(
                    provider="fnet_cvm",
                    role="regulatory",
                    priority=1,
                    url="https://fnet.bmfbovespa.com.br/",
                ),
                SourceRef(
                    provider="b3",
                    role="market_validation",
                    priority=4,
                    url="https://www.b3.com.br/",
                ),
            ),
        ),
        AssetRef(
            ticker="CDII11",
            asset_class="FI-Infra",
            asset_subtype="Infra",
            segment=None,
            manager="Sparta",
            sources=(
                SourceRef(
                    provider="sparta",
                    role="institutional_primary",
                    priority=3,
                    url="https://sparta.com.br/sparta-cdii11",
                ),
                SourceRef(
                    provider="fnet_cvm",
                    role="regulatory",
                    priority=1,
                    url="https://fnet.bmfbovespa.com.br/",
                ),
                SourceRef(
                    provider="b3",
                    role="market_validation",
                    priority=4,
                    url="https://www.b3.com.br/",
                ),
            ),
        ),
        AssetRef(
            ticker="CRAA11",
            asset_class="FI-Agro",
            asset_subtype="Agro",
            segment=None,
            manager="Sparta",
            sources=(
                SourceRef(
                    provider="sparta",
                    role="institutional_primary",
                    priority=3,
                    url="https://sparta.com.br/craa11",
                ),
                SourceRef(
                    provider="fnet_cvm",
                    role="regulatory",
                    priority=1,
                    url="https://fnet.bmfbovespa.com.br/",
                ),
                SourceRef(
                    provider="b3",
                    role="market_validation",
                    priority=4,
                    url="https://www.b3.com.br/",
                ),
            ),
        ),
    )
